### ISSUE TITLE
UDMH + NTO Configuration

### ISSUE THREAD

**Issue by Tyaedalis** [ferram4/ProcEngines#5]
I'm having some trouble finding much data on this particular mixture. A lot of Russian engines use it, but there's very little information about them (in my searches). Many other cases include either a different form of hydrazine or nitric acid (e.g. UDMH + RFNA, Aerozine-50 + NTO), which appear to be extremely similar, but I'm not knowledgeable enough in this area to know if these are similar enough to make a huge difference for your purposes.

### Parameters:
- **O/F range**: 0.5–60
- **Optimal O/F range**: 1.8–3.5
- **Frozen Area Ratio**: 1.5
- **Pressure range**: 0.25–100 MPa

### O/F Ratios to Calculate

- [x] 0.5
- [x] 0.8
- [x] 1.0
- [x] 1.3
- [x] 1.6
- [x] 1.8
- [x] 1.9
- [x] 2.0
- [x] 2.1
- [x] 2.2
- [x] 2.3
- [x] 2.4
- [x] 2.5
- [x] 2.6
- [x] 2.7
- [x] 2.8
- [x] 2.9
- [x] 3.0
- [x] 3.1
- [x] 3.2
- [x] 3.3
- [x] 3.4
- [x] 3.5
- [x] 4.0
- [x] 5.0
- [x] 7.5
- [x] 10.0
- [x] 20.0
- [x] 30.0
- [x] 40.0
- [x] 50.0
- [x] 60.0 (Partial)

**Comment by ferram4** [comment]
They're all very similar, which is the reason why I have this one down with a note in the wishlist that similar mixtures would be nice in the future, but aren't crucial now.  You should be able to roughly mix-and-match the O/F ratios and pressures for the different combos if you're looking for typical O/F and pressure data.  I would recommend [Norbert Brügge's site](http://www.b14643.de/) for info; under specials he has data for a lot of rocket engines, including mixture ratios.

I'd say to try doing the same pressure ratios as you did for hydrolox, but to extend the O/F range up a lot higher.  I think hypergolics tend to run ox-rich in the turbopumps.

**Comment by Tyaedalis** [comment]
That website is amazing. Wish I knew about it sooner!

**Comment by Tyaedalis** [comment]
That website is amazing. Wish I knew about it sooner!

**Comment by ferram4** [comment]
I would go higher for the O/F.  Water shows up in the exhaust, but it doesn't have the (L) after it, so it's gaseous and not a problem.  I think you could probably go all the way up to 60 and everything will be fine.

**Comment by Tyaedalis** [comment]
I'm getting H2O(L) at around 51. Should I still go with 60?

**Comment by ferram4** [comment]
It's only showing up at the end of the nozzle at high pressures, so yeah, keep going for 60.

**Comment by Tyaedalis** [comment]
I can only get data for 0.25 Pa chamber pressure up to a mixture ratio of 54. Above that, it's too cold. Am I doing something wrong, perhaps?

**Comment by ferram4** [comment]
No, likely that's just what's supposed to happen.  In that case, cut it off there.  If it's too cold to keep running, its chamber pressure should be cool enough to go into a turbine.  Chamber pressure is somewhere below ~800 K, right?

**Comment by Tyaedalis** [comment]
I can get data for down to 1.65 MPa with 60 O/F. At that point the temp in the chamber is ~600 K.

**Comment by ferram4** [comment]
Fill that table if you want, but leave it commented out if you can't complete the pressures.  I'm currently not supporting incomplete pressure listings for given O/Fs because it makes solving things simpler.  The data is useful, but maybe for later on.

**Comment by Tyaedalis** [comment]
Sure thing.

**Comment by ferram4** [comment]
And closed.

**Comment by Tyaedalis** [comment]
I just need to go over this again and we'll be good to go with these initial propellants!
