### ISSUE TITLE
CH4+LOX Configuration

### ISSUE THREAD

**Issue by dgeastman** [ferram4/ProcEngines#9]
**Parameters:**

**O/F range:** 0.15–55
**Optimal O/F range:** 2.5–4.0
**Frozen Area Ratio:** 2.0
**Pressure range:** 0.25–100 MPa

**O/F values to calculate:**
- [x] 0.15
- [x] 0.50
- [x] 1.00
- [x] 1.50
- [x] 2.00
- [x] 2.50
- [x] 2.60
- [x] 2.70
- [x] 2.80
- [x] 2.90
- [x] 3.00
- [x] 3.10
- [x] 3.20
- [x] 3.30
- [x] 3.40
- [x] 3.50
- [x] 3.60
- [x] 3.70
- [x] 3.80
- [x] 3.90
- [x] 4.00
- [x] 4.25
- [x] 4.50
- [x] 5.00
- [x] 10.00
- [x] 15.00
- [x] 25.00
- [x] 35.00
- [x] 45.00
- [x] 55.00

**Comment by ferram4** [comment]
Closed by #10
